<a href="https://colab.research.google.com/github/sandhya842/week1-AI-/blob/main/week1workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

problem1


In [ ]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
a = np.empty(array.shape)
print(a)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


In [ ]:
import numpy as np
array = np.array(([1,2],[3,4],[5,6],[7,8]))
a = np.zeros(array.shape)
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
new_array = np.array(([1,2],[3,4],[5,6],[7,8]))
a = np.full(new_array.shape, 4)
print(a)

[[4 4]
 [4 4]
 [4 4]
 [4 4]]


In [ ]:
import numpy as np
array = np.array(([1,2],[3,4],[5,6],[7,8]))
a = np.zeros_like(array.shape)
print(a)


[0 0]


In [ ]:
import numpy as np
array = np.array(([1,2],[3,4],[5,6],[7,8]))
a = np.ones_like(array.shape)
print(a)


[1 1]


In [ ]:
import numpy as np
new_list = [1,2,3,4,5]
a = np.array(new_list)
print(a)

[1 2 3 4 5]


problem 2

In [ ]:
import numpy as np
array = np.arange(10, 49)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
import numpy as np
array = np.arange(9).reshape(3,3)

print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
array = np.random.random(30)
mean = array.mean()
print("array: ", array)
print("mean: ",mean)



array:  [0.92701198 0.84375337 0.2871873  0.05506029 0.85278194 0.99873368
 0.63340463 0.98014491 0.76255517 0.56821325 0.86991962 0.27384926
 0.8706104  0.52024869 0.10089389 0.84859428 0.6955787  0.64782374
 0.84428685 0.76843615 0.03741983 0.74344072 0.34532588 0.17255617
 0.41078117 0.19586383 0.1600272  0.86993336 0.40624477 0.72424446]
mean:  0.5804975166208114


In [ ]:
import numpy as np
array = np.random.random((10,10))
minValue= array.min()
maxValue= array.max()
print("array:",array)
print("min value:",minValue)
print("max value:",maxValue)


array: [[0.89771825 0.64563412 0.18026106 0.21521536 0.46521197 0.43838161
  0.30429978 0.27271076 0.32581506 0.15974608]
 [0.15021895 0.8655011  0.04263048 0.73730363 0.79538443 0.32111936
  0.16298798 0.80697422 0.95369777 0.17926852]
 [0.59798213 0.54769204 0.62495625 0.49061544 0.29021819 0.97813822
  0.19064278 0.77681922 0.07113019 0.1012401 ]
 [0.95283789 0.72278652 0.37041004 0.92820564 0.38812743 0.4082615
  0.11655305 0.01110271 0.21114823 0.40232394]
 [0.40729959 0.23047954 0.65407575 0.34934948 0.13226158 0.12166219
  0.083859   0.83427234 0.65629272 0.46482082]
 [0.35557608 0.58373192 0.42154397 0.470765   0.44044833 0.08522349
  0.71513851 0.05753675 0.0498046  0.16736521]
 [0.88229577 0.83031925 0.90485012 0.11816484 0.9105479  0.9173446
  0.23304414 0.3336435  0.39288678 0.72455608]
 [0.35835017 0.28006743 0.43938185 0.70925655 0.53213872 0.89506662
  0.63776586 0.09633148 0.14626214 0.42204893]
 [0.87127882 0.45643354 0.35300656 0.88995334 0.86081629 0.21709548
  0.669

In [ ]:
import numpy as np
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
array = np.array([1,2,0,0,4,0])
rev_array = array[::-1]
print(rev_array)

[0 4 0 0 2 1]


In [ ]:
import numpy as np
array = np.ones((4,4))
array[1:-1,1:-1] =0
print(array)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


problem3

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
add = x+y
print("add:",add)
sub = x-y
print("sub:",sub)
mul = x*y
print("mul:",mul)
square = x**2
print("square:",square)
dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)
dot_xv = np.dot(x, v)
print("Dot product of x and v:\n", dot_xv)
dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)
concat_xy_row = np.concatenate((x, y), axis=0)
print("x and y concatenated along rows:\n", concat_xy_row)
v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)
concat_vw_col = np.concatenate((v_col, w_col), axis=1)
print("v and w concatenated along columns:\n", concat_vw_col)

concat_xv_fixed = np.concatenate((x, v.reshape(1,2)), axis=0)
print("x and v concatenated after reshaping v:\n", concat_xv_fixed)





add: [[ 6  8]
 [10 13]]
sub: [[-4 -4]
 [-4 -3]]
mul: [[ 5 12]
 [21 40]]
square: [[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
x and y concatenated along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w concatenated along columns:
 [[ 9 11]
 [10 12]]
x and v concatenated after reshaping v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


In [ ]:
import numpy as np

A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

A_inv = np.linalg.inv(A)


identity = np.dot(A, A_inv)

print("A * A^-1 =\n", identity)
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)
print("AB == BA ?", np.array_equal(AB, BA))
AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)

print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)
print("(AB)^T == B^T A^T ?", np.array_equal(AB_T, BT_AT))




A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB == BA ? False
(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
(AB)^T == B^T A^T ? True


In [ ]:

A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])


B_eq = np.array([-1, -3, 9])

A_inv_eq = np.linalg.inv(A_eq)


X = np.dot(A_inv_eq, B_eq)

print("Solution [x, y, z]:", X)



Solution [x, y, z]: [ 2.  1. -2.]
